[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "espressocharts"
version = "0.1.0"
description = "Espresso Charts visual engine"
authors = [{name = "SH"}]
dependencies = [
    "pandas",
    "matplotlib",
    "numpy"
]
